---
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

name: Documentation Request
description: File a documentation request so we better understand how to implement it.
title: "doc(<scope>): <title>"
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a documentation request.
        Please fill out the following information about the documentation you are requesting.
        Also please make sure that the `<scope>` and `<title>` in the title are correct.
        If you are not sure about anything, please ask @Inetum-Poland/devops-admins or @aamkye.

  # Context
  - type: textarea
    id: context-documentation
    attributes:
      label: Context
      description: Provide "Big Picture" for the documentation.
      placeholder: Provide background, goals, or any relevant information that helps understand the documentation request.
    validations:
      required: true

  # Why
  - type: textarea
    id: why-documentation
    attributes:
      label: Why is this documentation needed?
      description: Explain the problem and why it should be in documentation.
      placeholder: I need to be able to do X because Y, how to do it?
    validations:
      required: true

  # What
  - type: textarea
    id: what-documentation
    attributes:
      label: What will this documentation cover?
      description: Please explain what should this documentation cover.
      placeholder: Ex. supervision, sending messages, texter profiles.
    validations:
      required: true

  # Who
  - type: textarea
    id: who-documentation
    attributes:
      label: Who will this documentation benefit?
      description: Please explain who will this documentation benefit.
      placeholder: Ex. All supervisors, Sally Supervisor, Level 1 CCs.
    validations:
      required: true


  # Other Comments
  - type: textarea
    id: other-comments
    attributes:
      label: Other Comments / Logs
      description: Please explain anything else that you think is relevant.
